GradeProject.AuthService/Models/Clients/ApiInsertModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace GradeProject.AuthService.Models.Clients
{
    public class ApiInsertModel
    {
    }
}

GradeProject.AuthService/Models/Clients/ClientCredentials.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace GradeProject.AuthService.Models.Clients
{
    public class ClientCredentials
    {
        public string ClientId { get; set; }
        public string ClientSecret { get; set; }

        public ClientCredentials(string clientId, string clientSecret)
        {
            ClientId = clientId;
            ClientSecret = clientSecret;
        }
    }
}

GradeProject.AuthService/Models/Clients/ClientInsertModel.cs
using Microsoft.AspNetCore.Http;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace GradeProject.AuthService.Models.Clients
{
    public class ClientInsertModel
    {
        public ClientInsertModel()
        {
        }

        public string ClientName { get; set; }
        public IFormFile ClientLogo { get; set; }
        public string LogoUri { get; set; }

        public string Type { get; set; }
        public string ClientUri { get; set; }
        public string RedirectUris { get; set; }
        public string PostLogoutUris { get; set; }

        //public string RequiredScopes { get; set; }
    }
}

GradeProject.AuthService/Models/Clients/UserClientDTO.cs
using GradeProject.AuthService.Infrastructure;
using IdentityServer4.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace GradeProject.AuthService.Models.Clients
{
    public class UserClientDTO
    {
        public UserClientDTO()
        {

        }

        public string Type { get; set; }

        public string ClientId { get; set; }
        public string ClientName { get; set; }
        public string LogoUri { get; set; }
        public string Secret { get; set; }
    }
}

GradeProject.AuthService/Controllers/ClientsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using GradeProject.AuthService.Infrastructure;
using GradeProject.AuthService.Models.Clients;
using Microsoft.AspNetCore.Mvc;
using IdentityServer4.Models;
using System.IO;
using IdentityServer4;
using System.Security.Claims;
using Microsoft.AspNetCore.Authorization;
using System.Net.Http;
using GradeProject.AuthService.Models.Account;
using Newtonsoft.Json;
using GradeProject.AuthService.Infrastructure.Clients;

namespace GradeProject.AuthService.Controllers
{
    [Authorize]
    //[Authorize(Policy = "DevelopersOnly")]dd
    public class ClientsController : Controller
    {
        private readonly IClientService _clientSvc;
        private readonly IMapper _mapper;
        private readonly IApiManagmentService _apiMng;
        private readonly IFilesSaveService _filesSvc;
        private Guid _userId;

        public ClientsController(
            IClientService clientSvc,
            IMapper mapper,
            IFilesSaveService filesSvc,
            IApiManagmentService apiMng)
        {
            _clientSvc = clientSvc;
            _mapper = mapper;
            _apiMng = apiMng;
            _filesSvc = filesSvc;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            _userId = Guid.Parse(User.Claims.FirstOrDefault(c => c.Type == "sub").Value);
            var clients = await _clientSvc.GetUserClients(_userId);
            return View(clients);
        }


        [HttpGet]
        [Authorize]
        public IActionResult NewClient(string pass = "none")
        {
            ViewData["password"] = pass;
            return View();
        }

        [HttpGet]
        [Authorize]
        public IActionResult Add(string type = "oauth-client")
        {
            return View(new ClientInsertModel() { Type = type });
        }

        //Add granual authorization
        [HttpPost]
        [Authorize]
        public async Task<IActionResult> Add(ClientInsertModel clientDto)
        {
            _userId = Guid.Parse(User.Claims.FirstOrDefault(c => c.Type == "sub").Value);

            if (clientDto.Type.Equals("oauth-client") && clientDto.ClientLogo != null)
            {
                var fileName = $"images/Clients/{Guid.NewGuid()}{Path.GetExtension(clientDto.ClientLogo.FileName)}";
                await _filesSvc.SaveFile(fileName, clientDto.ClientLogo);
                clientDto.LogoUri = fileName;
            }

            var pwd = _clientSvc.AddClient(clientDto, _userId);

            return RedirectToAction(nameof(NewClient), new { pass = pwd });
        }
    }
}

GradeProject.AuthService/Views/Clients/Add.cshtml
@model GradeProject.AuthService.Models.Clients.ClientInsertModel

@{
    ViewData["Title"] = "Add";
}

<div class="wrapper">
    <h2>Add</h2>

    <p>
        Choose your type :
        @Html.ActionLink("oauth-client", "Add", "Clients", new { type = "oauth-client" }, null) |
        @Html.ActionLink("application", "Add", "Clients", new { type = "application" }, null)
    </p>
    <h4>ClientInsertModel</h4>
    <hr />

    @*<form asp-action="Add" enctype="multipart/form-data">
        <div class="col-md-6">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" name="Type" value="@Model.Type" />*@
            @*<div class="form-group">
            <label asp-for="ClientId" class="control-label"></label>
            <input asp-for="ClientId" class="form-control" value="client-@Guid.NewGuid()" />
            <span asp-validation-for="ClientId" class="text-danger"></span>
        </div>*@
            @*@if (!Model.Type.Equals("oauth-client"))
            {
                <div class="form-group">
                    <label asp-for="ClientSecret" class="control-label"></label>
                    <input asp-for="ClientSecret" class="form-control" value="secret-@Guid.NewGuid()" />
                    <span asp-validation-for="ClientSecret" class="text-danger"></span>
                </div>
            }
            @if (Model.Type.Equals("oauth-client"))
            {
                <div class="form-group form-group-client-image">
                    <label class="control-label">Image</label>
                    <div class="inputs">
                        <img id="client-image" src="http://docs.identityserver.io/en/release/_images/logo.png" alt="your image" />
                        <input id="image-selector" type="file" name="ClientLogo" />
                    </div>
                </div>
                <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label ">
                    <input class="mdl-textfield__input" name="ClientName" type="text" id="sample3">
                    <label class="mdl-textfield__label" for="sample3">Display Name</label>
                </div>
                <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label form-input">
                    <textarea class="mdl-textfield__input" type="text" cols="5" id="sample3"></textarea>
                    <label class="mdl-textfield__label" for="sample3">Description</label>
                </div>
            }
        </div>
        <div class="col-lg-6">
            @if (Model.Type.Equals("oauth-client"))
            {                
                <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label form-input">
                    <textarea class="mdl-textfield__input" name="RedirectUris" type="text" id="sample3"></textarea>
                    <label class="mdl-textfield__label" for="sample3">Redirect Uris</label>
                </div>
                <div class="form-group">
                    <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label form-input">
                        <textarea class="mdl-textfield__input" type="text" id="sample3"></textarea>
                        <label class="mdl-textfield__label" for="sample3">Post Logout Uris</label>
                    </div>
                </div>
            }
        </div>
        <div class="form-group col-md-12">
            <div>
                <a asp-action="Index">Back Clients</a>
            </div>
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </form>*@

    @*<form action="/" method="post" class="form-app-register">
            <div class="col-md-6">
                <div class="oauth-clien-credentials">
                    <label>ClientKey : </label>
                    <label>client-@Guid.NewGuid()</label>
                </div>
                <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
                    <input class="mdl-textfield__input" type="text" id="sample3">
                    <label class="mdl-textfield__label" for="sample3">Client Name</label>
                </div>
            </div>
            <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
                <input class="mdl-textfield__input" type="text" id="sample3">
                <label class="mdl-textfield__label" for="sample3">Client Info Uri</label>
            </div>
            <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
                <textarea class="mdl-textfield__input" type="text" rows="3" id="sample5"></textarea>
                <label class="mdl-textfield__label" for="sample5">Redierct Uris</label>
            </div>
            <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
                <textarea class="mdl-textfield__input" type="text" rows="3" id="sample5"></textarea>
                <label class="mdl-textfield__label" for="sample5">Post Logout Uris</label>
            </div>
        </form>*@


    <style>
        .form-label-clientId {
            width: 100%;
        }

        .oauth-clien-credentials {
            display: flex;
            flex-direction: row;
        }

        .form-app-register {
            color: black;
            width: 100%;
            /*display: flex;
                flex-direction: column;
                align-items: center;*/
        }

        .form-label-simple {
            font-family: "Roboto", sans-serif;
        }

        .form-input {
            width: 100%;
        }

        .mdl-textfield__label {
            margin-bottom: 0px;
        }

        .mdl-textfield__label {
            font-family: 'Roboto', sans-serif;
            font-size: 15px;
            font-weight: 500;
        }
    </style>

    <form asp-action="Add" enctype="multipart/form-data">
        <div class="col-md-6">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" name="Type" value="@Model.Type" />
            @*<div class="form-group">
            <label asp-for="ClientId" class="control-label"></label>
            <input asp-for="ClientId" class="form-control" value="@Guid.NewGuid()" />
            <span asp-validation-for="ClientId" class="text-danger"></span>
        </div>
        @if (!Model.Type.Equals("oauth-client"))
        {
            <div class="form-group">
                <label asp-for="ClientSecret" class="control-label"></label>
                <input asp-for="ClientSecret" class="form-control" value="secret-@Guid.NewGuid()" />
                <span asp-validation-for="ClientSecret" class="text-danger"></span>
            </div>
        }*@
            <div class="form-group">
                <label asp-for="ClientName" class="control-label"></label>
                <input asp-for="ClientName" class="form-control" />
                <span asp-validation-for="ClientName" class="text-danger"></span>
            </div>
                <div class="form-group form-group-client-image">
                    <label class="control-label">Image</label>
                    <div class="inputs">
                        <input id="image-selector" type="file" name="ClientLogo" />
                        <img id="client-image" src="http://docs.identityserver.io/en/release/_images/logo.png" alt="your image" />
                    </div>
                </div>
        </div>
        <div class="col-lg-6">
            @if (Model.Type.Equals("oauth-client"))
            {
                <div class="form-group">
                    <label asp-for="ClientUri" class="control-label"></label>
                    <input asp-for="ClientUri" class="form-control" />
                    <span asp-validation-for="ClientUri" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="RedirectUris" class="control-label"></label>
                    <input asp-for="RedirectUris" class="form-control" />
                    <span asp-validation-for="RedirectUris" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="PostLogoutUris" class="control-label"></label>
                    <input asp-for="PostLogoutUris" class="form-control" />
                    <span asp-validation-for="PostLogoutUris" class="text-danger"></span>
                </div>
            }
        </div>
        <div class="form-group col-md-12">
            <div>
                <a asp-action="Index">Back Clients</a>
            </div>
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </form>

</div>

<style>
    .wrapper {
        margin-top: 55px;
    }
</style>

<script type="text/javascript">

    function readURL(input) {

        if (input.files && input.files[0]) {

            var reader = new FileReader();



            reader.onload = function (e) {

                $('#client-image').attr('src', e.target.result);

            }

            reader.readAsDataURL(input.files[0]);

        }

    }

    $("#image-selector").change(function () {
        readURL(this);

    });

</script>

GradeProject.AuthService/Views/Clients/Index.cshtml
@model IEnumerable<GradeProject.AuthService.Models.Clients.UserClientDTO>

@{
    ViewData["Title"] = "Index";
}

<h2>Clients</h2>

<hr />
<div class="row">
    <div class="row placeholder-menu">
        <button class="mdl-button mdl-js-button">
            <i class="material-icons">
                add_box
            </i> Add new
        </button>
    </div>

    @foreach (var client in Model)
    {
        <div class="mdl-card mdl-card mdl-card--border mdl-shadow--2dp user-client-card col-md-4">
            <div class="mdl-card__title">
                <h2 class="mdl-card__subtitle-text">@client.ClientName</h2>

            </div>
            <div class="mdl-card__media user-client-card-image" style="background-image: url(~/../..@client.LogoUri)">
            </div>
            <div class="mdl-card__supporting-text">
                <p>Client Id : @client.ClientId</p>
                @if (client.Type == "application")
                {
                    <p>Client Secret : @client.Secret</p>
                }
            </div>
            <div class="mdl-card__menu">
                <p>@client.Type</p>
            </div>
        </div>
    }


    <div class="mdl-card new-client-card mdl-card mdl-card--border mdl-shadow--2dp user-client-card col-md-4">
        <div class="mdl-card__media user-client-card-image">
            <a href="/Clients/Add">
                <i class="material-icons">
                    add_box
                </i>
            </a>
        </div>
    </div>

    @*<form asp-action="Index">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="col-md-6">*@
    @*<div class="form-group">
            <label asp-for="ClientId" class="control-label"></label>
            <input asp-for="ClientId" class="form-control" value="@Guid.NewGuid().ToString()" />
            <span asp-validation-for="ClientId" class="text-danger"></span>
        </div>*@
    @*</div>
        <div class="col-md-4">*@
    @*<div class="form-group">
            <label asp-for="RedirectUris" class="control-label"></label>
            <input asp-for="RedirectUris" class="form-control" />
            <span asp-validation-for="RedirectUris" class="text-danger"></span>
        </div>*@
    @*<div class="form-group">
            <label asp-for="PostLogoutUris" class="control-label"></label>
            <input asp-for="PostLogoutUris" class="form-control" />
            <span asp-validation-for="PostLogoutUris" class="text-danger"></span>
        </div>*@
    @*</div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>*@

</div>

<style>

    .row {
        display: flex;
        flex-direction: row;
        flex-wrap: wrap;
    }

    .user-client-card {
        margin: 15px;
    }

    .user-client-card-image {
        width: 100%;
        height: 250px;
        background-color: white;
        background-size: cover;
    }

    .placeholder-menu {
        width: 100%;
        margin-left: 5px;
    }

        .placeholder-menu i {
            color: #373737;
        }

    .new-client-card {
        line-height: 40px;
    }

        .new-client-card a {
        }

        .new-client-card i {
            position: absolute;
            top: 50%;
            left: 50%;
            transform: translate(-50%, -50%);
            font-size: 40px;
        }
</style>

GradeProject.AuthService/Views/Clients/NewClient.cshtml
@{
    ViewData["Title"] = "NewClient";
}

<h2>NewClient</h2>

Client Pass @ViewData["password"]

<br />@Html.ActionLink("Go to clients", "Index", "Clients")